# Generated by Django 3.2.3 on 2021-06-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='query',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
