# Generated by Django 3.2.3 on 2021-06-03 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210603_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderline',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
