# Generated by Django 3.2.3 on 2021-06-03 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_quatity_orderline_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='shiping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.shipping'),
        ),
    ]
