# Generated by Django 3.2.3 on 2021-06-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_rename_shiping_order_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.AlterField(
            model_name='shipping',
            name='shipStatus',
            field=models.CharField(choices=[('SHIPPING', 'SHIPPING'), ('DONE', 'DONE'), ('PROCESSING', 'PROCESSING')], default='PROCESSING', max_length=200),
        ),
    ]
