# Generated by Django 3.2.3 on 2021-06-09 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_importedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedproduct',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.warehouse'),
        ),
    ]
