# Generated by Django 3.2.3 on 2021-06-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_ordernotification_ordernotificationaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinstock',
            name='importPrice',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
