# Generated by Django 3.2.3 on 2021-06-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_shipping_shipstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderfeedback',
            name='quanlity',
        ),
        migrations.RemoveField(
            model_name='orderfeedback',
            name='store',
        ),
        migrations.AddField(
            model_name='orderfeedback',
            name='quality',
            field=models.CharField(choices=[(1, 'Rât tệ'), (2, 'Tệ'), (3, 'Ổn'), (4, 'Tốt'), (5, 'Rất tốt')], default=5, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderfeedback',
            name='action',
            field=models.CharField(choices=[(1, 'Trả hàng'), (2, 'Không')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderfeedback',
            name='isFeedback',
            field=models.BooleanField(default=False),
        ),
    ]
