# Generated by Django 3.2.3 on 2021-06-17 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20210617_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfeedback',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
