# Generated by Django 3.2.3 on 2021-06-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_auto_20210618_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfeedback',
            name='action',
            field=models.IntegerField(choices=[(1, 'Trả hàng'), (2, 'Không')]),
        ),
        migrations.AlterField(
            model_name='orderfeedback',
            name='quality',
            field=models.IntegerField(choices=[(1, 'Rât tệ'), (2, 'Tệ'), (3, 'Ổn'), (4, 'Tốt'), (5, 'Rất tốt')]),
        ),
    ]
